/**
 * theme/tokens.ts — tactile starter tokens. A non-generic, WCAG-AA-verified baseline so
 * every mobile build starts DESIGNED, not default. The ONLY file allowed to hold raw hex
 * (tactile AR-T05): screen code references these tokens, never a literal colour.
 *
 * Runtime-proven 2026-06-26: the tactile token system was rendered in a live Expo SDK 56 app
 * (RN 0.85) on Android — light + dark via useColors(), retinted across hues with all 42 AA pairs
 * holding, strict tsc clean. Integration gotcha the render caught: set app.json
 * "userInterfaceStyle": "automatic", or the OS dark-mode setting never reaches useColorScheme()
 * and the dark palette below stays dormant.
 *
 * Generated by skills/tactile/scripts/generate-tokens.mjs at brand hue 185°.
 * To retint: change BRAND_H in that script, re-run to confirm AA, then re-emit — do not
 * hand-edit the hex (the generator is the source of truth and the contrast proof).
 *
 * NativeWind-version-agnostic by design: NativeWind v5 (Tailwind-v4 @theme) is still
 * preview-only as of mid-2026 (npm view nativewind dist-tags → latest 4.2.6 / preview 5.x),
 * so these are plain typed StyleSheet tokens — they work with StyleSheet, NativeWind v4,
 * a future v5, or no styling lib at all. See app-dev/stack.md for the version trap.
 *
 * Change exactly two things for a new project: (1) the brand hue (regenerate), and
 * (2) the three font faces below (run tactile's <font_selection_procedure> first).
 *
 *   import { useColors, type, space, radius, elevation, motion, touch } from '@/theme/tokens';
 *   const c = useColors();                 // light/dark picked from the system setting
 *   <View style={{ backgroundColor: c.surface, padding: space.gutter, ...elevation.md }}>
 *     <Text style={[type.label, { color: c.onSurfaceVariant }]}>TODAY</Text>
 *     <Text style={[type.display, { color: c.onSurface }]}>1,840 ml</Text>
 *   </View>
 */
import { Platform, useColorScheme, type TextStyle, type ViewStyle } from 'react-native';

// ── Colour — MD3 role system, light + dark. Every `on*` is AA-legible on its surface. ──
export const palette = {
  light: {
    surface:            '#f7fbfa',
    surfaceRaised:      '#fbfefe',
    surfaceVariant:     '#e4ebea',
    onSurface:          '#131d1b',
    onSurfaceVariant:   '#495654',
    outline:            '#707a78',
    outlineVariant:     '#c8cfce',
    primary:            '#037a70',
    onPrimary:          '#f5fefd',
    primaryContainer:   '#bae9e2',
    onPrimaryContainer: '#013c37',
    error:              '#c13c3b',
    onError:            '#fffafa',
    errorContainer:     '#ffd6d2',
    onErrorContainer:   '#621d1c',
    success:            '#2c7f44',
    onSuccess:          '#f7fef8',
    successContainer:   '#cbebd0',
    onSuccessContainer: '#093e1b',
    warning:            '#d18e35',
    onWarning:          '#211201',
    warningContainer:   '#ffdeba',
    onWarningContainer: '#54360b',
    info:               '#2f72b1',
    onInfo:             '#f9fcff',
    infoContainer:      '#cbe4ff',
    onInfoContainer:    '#113a5f',
    shadow:             '#071413',
  },
  dark: {
    surface:            '#0a0e0e',
    surfaceRaised:      '#141a19',
    surfaceVariant:     '#242b29',
    onSurface:          '#e4e9e8',
    onSurfaceVariant:   '#acb7b5',
    outline:            '#737d7b',
    outlineVariant:     '#383f3e',
    primary:            '#69d3c6',
    onPrimary:          '#002622',
    primaryContainer:   '#00423c',
    onPrimaryContainer: '#bae9e2',
    error:              '#eb827b',
    onError:            '#2e100e',
    errorContainer:     '#5b1e1c',
    onErrorContainer:   '#fed2cd',
    success:            '#82cb92',
    onSuccess:          '#06210d',
    successContainer:   '#133c1f',
    onSuccessContainer: '#c8e8cd',
    warning:            '#f6b669',
    onWarning:          '#2e1a01',
    warningContainer:   '#4f3005',
    onWarningContainer: '#fbe0c1',
    info:               '#85bcf5',
    onInfo:             '#061c31',
    infoContainer:      '#153758',
    onInfoContainer:    '#c6e1ff',
    shadow:             '#000100',
  },
} as const;

// Widen to string values (the palette is `as const`, so `typeof palette.light` would be the LIGHT
// hex *literals* — then returning palette.dark wouldn't assign). Keys stay exact for autocomplete.
export type Colors = Record<keyof typeof palette.light, string>;

/** Pick the colour set for a scheme (the RN analog of CSS `light-dark()`). */
export const getColors = (scheme: 'light' | 'dark' | null | undefined): Colors =>
  scheme === 'dark' ? palette.dark : palette.light;

/** Hook: follow the system light/dark setting. Pin a single theme here if the brief calls for it. */
export function useColors(): Colors {
  // useColorScheme() can return 'unspecified' (and null under the strict API) — narrow to the two we map.
  return getColors(useColorScheme() === 'dark' ? 'dark' : 'light');
}

// ── Typography — three roles you actually mount per screen (display / body / label). ──
// Hierarchy is weight + colour at one size, never a 4th size (AR-T16). Run tactile's
// <font_selection_procedure> (SKILL.md) before naming a face — do NOT ship the reflex set.
export const fonts: { display?: string; body?: string; bodyLong?: string } = {
  // e.g. display: 'ClashDisplay_600SemiBold', body: 'Inter_400Regular'. Until set, RN uses
  // the platform face (SF Pro / Roboto) — acceptable for scaffolding, NOT for shipping.
};

export const type = {
  display:  { fontFamily: fonts.display, fontSize: 34, lineHeight: 38, letterSpacing: -0.5, fontWeight: '800' },
  headline: { fontFamily: fonts.display, fontSize: 24, lineHeight: 28, letterSpacing: -0.3, fontWeight: '700' },
  title:    { fontFamily: fonts.display, fontSize: 17, lineHeight: 22, letterSpacing: 0,    fontWeight: '700' },
  body:     { fontFamily: fonts.body,    fontSize: 16, lineHeight: 24, letterSpacing: 0,    fontWeight: '400' },
  bodyLong: { fontFamily: fonts.bodyLong ?? fonts.body, fontSize: 16, lineHeight: 26, letterSpacing: 0, fontWeight: '300' },
  label:    { fontFamily: fonts.body,    fontSize: 12, lineHeight: 16, letterSpacing: 1.4,  fontWeight: '600',
              textTransform: 'uppercase' },
} satisfies Record<string, TextStyle>;

// ── Spacing — 4/8pt grid, named by intent. Never compress the canonical four (mobile-spacing.md). ──
export const space = {
  xs: 4,        // icon↔label, chip inner
  sm: 8,        // related items in a group
  md: 12,       // card-padding floor — never below this
  base: 16,     // default internal padding
  glassPad: 20, // internal padding for glass cards
  gutter: 24,   // page horizontal gutter (canonical — 20 acceptable, below 16 is cramped)
  lg: 32,       // large card / between cards
  stackLg: 40,  // breath between distinct vertical sections — the IA separator
  xl: 56,       // hero offset
} as const;

// ── Radius — squircle scale by role (glass-and-depth.md). Keep nested radii concentric. ──
export const radius = {
  chip: 12,     // inputs / small chips
  card: 18,     // standard cards
  cardLg: 22,   // glass / larger cards
  feature: 28,  // large feature cards
  pill: 999,    // buttons / pills / fully-rounded
} as const;

// ── Elevation — ALWAYS sets both iOS shadow* and Android elevation (AR-T20). Shadow colour is a ──
// brand-tinted near-black (never a flat pure black), soft + ambient: big radius + low opacity = expensive lift.
const SHADOW = palette.light.shadow; // brand-tinted near-black shadow — retints with BRAND_H
export const elevation = {
  sm: Platform.select({
    ios: { shadowColor: SHADOW, shadowOpacity: 0.06, shadowRadius: 8,  shadowOffset: { width: 0, height: 2 } },
    android: { elevation: 2 },
    default: {},
  }) as ViewStyle,
  md: Platform.select({
    ios: { shadowColor: SHADOW, shadowOpacity: 0.07, shadowRadius: 16, shadowOffset: { width: 0, height: 6 } },
    android: { elevation: 4 },
    default: {},
  }) as ViewStyle,
  lg: Platform.select({
    ios: { shadowColor: SHADOW, shadowOpacity: 0.10, shadowRadius: 24, shadowOffset: { width: 0, height: 12 } },
    android: { elevation: 8 },
    default: {},
  }) as ViewStyle,
} as const;

// ── Motion — native timing + ease-out/in curves. No bounce/elastic (AR-T30). ───────────
// Use the bezier tuples with Easing.bezier(...): import { Easing } from 'react-native-reanimated'.
export const motion = {
  duration: { instant: 0, press: 120, base: 240, exit: 200, slow: 320 }, // >300ms reads laggy
  easing: {
    out: [0.16, 1, 0.3, 1] as const,   // entrances decelerate into place
    in: [0.4, 0, 1, 1] as const,        // exits accelerate away
    inOut: [0.65, 0, 0.35, 1] as const,
  },
} as const;

// ── Touch targets — iOS 44pt / Android 48dp minimum hit region (app-dev/principles). ───
// Size the HIT AREA, not just the glyph; hitSlop(visible) pads a small control up to 48dp.
export const touch = {
  ios: 44,
  android: 48,
  min: 48, // 48 satisfies both platforms
  hitSlop(visible: number) {
    const pad = Math.max(0, Math.round((this.min - visible) / 2));
    return { top: pad, bottom: pad, left: pad, right: pad };
  },
} as const;

/*
 * WCAG-AA verified at brand H=185 (OKLCH→sRGB→WCAG, computed on the baked hex by
 * generate-tokens.mjs — re-run after any retint). Worst-case mounted pairs:
 *   LIGHT  body ≥ 4.8:1 · large/UI ≥ 3.6:1
 *   DARK   body ≥ 6.6:1 · large/UI ≥ 3.4:1
 * (AA floor: 4.5:1 body, 3:1 large-text/borders/icons.) Neutrals are near-zero chroma, so
 * their contrast is hue-stable; brand-on-surface IS hue-sensitive — warm yellow-green hues
 * (~90–140) make the brand more luminous, so re-run the generator after retinting and, if a
 * pair dips, lower the brand L (~0.46) or darken onPrimary.
 */
