#!/bin/bash
# Rebuild memory-bridge.yaml — indexes Progressive Learning topics for Flow agents.
# Called by session-start.sh. Parses INDEX.md tables into a YAML index so
# flow-learnings-researcher can find memory/topics/ entries efficiently.

MEMORY_DIR="$HOME/.claude/projects/C--Users-leooa--claude/memory"
INDEX_FILE="$MEMORY_DIR/INDEX.md"
OUTPUT_DIR="$HOME/.claude/flow-knowledge"
OUTPUT_FILE="$OUTPUT_DIR/memory-bridge.yaml"

# Skip if no INDEX.md
if [ ! -f "$INDEX_FILE" ]; then
  exit 0
fi

mkdir -p "$OUTPUT_DIR"

# Count entries first
ENTRY_COUNT=$(grep -cE '^\| G-(PAT|SOL|ERR|FAIL|PREF)-[0-9]+' "$INDEX_FILE" 2>/dev/null || echo "0")

# Write YAML header
cat > "$OUTPUT_FILE" << EOF
# Auto-generated by rebuild-memory-bridge.sh — do not edit manually
# Indexes Progressive Learning topics for Flow agent discovery
_meta:
  generated: "$(date +%Y-%m-%d)"
  source: "memory/INDEX.md"
  entry_count: $ENTRY_COUNT
entries:
EOF

# Parse each table row: | ID | Name | Summary | Tags | Date |
grep -E '^\| G-(PAT|SOL|ERR|FAIL|PREF)-[0-9]+' "$INDEX_FILE" | while IFS='|' read -r _ id name summary tags date _; do
  # Trim whitespace (sed instead of xargs to avoid quote issues)
  id=$(echo "$id" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
  name=$(echo "$name" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
  summary=$(echo "$summary" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
  tags=$(echo "$tags" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
  date=$(echo "$date" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')

  # Derive category from ID prefix
  case "$id" in
    G-PAT-*) category="pattern" ;;
    G-SOL-*) category="solution" ;;
    G-ERR-*) category="mistake" ;;
    G-FAIL-*) category="failed_approach" ;;
    G-PREF-*) category="preference" ;;
    *) category="unknown" ;;
  esac

  # Derive slug from name (lowercase, spaces to hyphens)
  slug=$(echo "$name" | tr '[:upper:]' '[:lower:]' | sed 's/ /-/g' | sed 's/[^a-z0-9-]//g')

  # Convert tags from "#tag1 #tag2" to "[tag1, tag2]"
  tag_list=$(echo "$tags" | sed 's/#//g' | xargs | sed 's/ /, /g')

  # Escape special YAML characters in summary
  summary_escaped=$(echo "$summary" | sed 's/"/\\"/g')

  cat >> "$OUTPUT_FILE" << EOF
  - id: "$id"
    category: "$category"
    name: "$name"
    tags: [$tag_list]
    summary: "$summary_escaped"
    path: "memory/topics/${id}-${slug}.md"
    date: "$date"
EOF
done
