#!/usr/bin/env node
/**
 * wiki-lint.js — persisted wiki health checker (F-07, v10).
 *
 * The weekly-wiki-lint task previously had the model improvise scan code every
 * run (CRLF false positives, heredoc-mangled paths — facet bfff879d). This is
 * the single engine; /wiki-lint and wiki-manage LINT mode are thin callers.
 *
 * Checks (filesystem only — npm/stack freshness stays in the skill layer):
 *   broken-related       frontmatter `related:` wikilink unresolved   error
 *   broken-mdlink        [text](path.md) target missing on disk       error
 *   phantom-index        index.md/_index.md row → nonexistent page    error
 *   no-frontmatter       page missing YAML frontmatter                warning
 *   frontmatter-keys     frontmatter missing title/type/updated       info
 *   stale                updated/mtime older than 90 days             warning
 *   orphan               no incoming wikilink/md-link/index path ref  info
 *   unresolved-wikilinks body [[links]] with no page (per-page count) info
 *
 * Body wikilinks are deliberately aspirational in this vault (KNOWLEDGE-ids,
 * planned pages — see CLAUDE.md memory conventions), so they are informational,
 * never errors. Only the documented `related:` check is error-severity.
 * Historical log pages (log.md) are exempt from link checks.
 *
 * Report-only by contract — this script NEVER edits the vault.
 * Deterministic: findings sorted, no timestamps in default output.
 * Usage: node scripts/wiki-lint.js [--json]
 */

'use strict';

const fs = require('fs');
const path = require('path');
const os = require('os');

const VAULT = path.join(os.homedir(), 'Documents', 'Wiki', 'wiki');
const STALE_DAYS = 90;
// Output/transcript dirs — never linted, but their pages still resolve links.
const SKIP_DIRS = new Set(['session-log', 'graph', 'graphify-out', 'TRASH']);
// Infrastructure pages: links are checked, but frontmatter/stale/orphan don't apply.
const INFRA = new Set(['index.md', '_index.md', 'hot.md', 'log.md', 'overview.md', 'TRASH-FILES.md']);
const AUTOGEN_MARKERS = ['Regenerated by', 'AUTO-GENERATED', 'Auto-generated by'];

function walk(dir, out) {
  let entries;
  try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch (_) { return out; }
  for (const e of entries) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) walk(full, out);
    else if (e.name.toLowerCase().endsWith('.md')) out.push(full);
  }
  return out;
}

function read(file) {
  // CRLF-normalize every read — the #1 false-positive source in ad-hoc linters.
  return fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n');
}

function stripCode(text) {
  // Remove fenced blocks and inline code so [[link]] examples in docs don't count.
  return text.replace(/```[\s\S]*?```/g, '').replace(/`[^`\n]*`/g, '');
}

function parseFrontmatter(text) {
  if (!text.startsWith('---\n')) return null;
  const end = text.indexOf('\n---', 4);
  if (end === -1) return null;
  const fm = {};
  for (const line of text.slice(4, end).split('\n')) {
    const m = line.match(/^([A-Za-z_][\w-]*):\s*(.*)$/);
    if (m) fm[m[1]] = m[2].trim();
  }
  return fm;
}

const allFiles = walk(VAULT, []);
const rel = f => path.relative(VAULT, f).replace(/\\/g, '/');

// Resolution sets: every page in the vault resolves links (incl. session-log);
// only the lint corpus gets checked.
const allRelPaths = new Set(allFiles.map(f => rel(f).toLowerCase()));
const basenames = new Set(allFiles.map(f => path.basename(f, path.extname(f)).toLowerCase()));

const lintFiles = allFiles.filter(f => {
  const r = rel(f);
  if (r.split('/').some(seg => SKIP_DIRS.has(seg))) return false;
  return true;
});

const pages = [];
const skippedAutogen = [];
for (const f of lintFiles) {
  const content = read(f);
  const head = content.slice(0, 600);
  const r = rel(f);
  if (path.basename(f) === 'hot.md' || AUTOGEN_MARKERS.some(m => head.includes(m))) {
    skippedAutogen.push(r);
    continue;
  }
  pages.push({ file: f, rel: r, content, base: path.basename(f), fm: parseFrontmatter(content) });
}

const findings = [];
const add = (severity, type, page, detail) => findings.push({ severity, type, page, detail });

// Incoming-reference map for orphan detection (built from the lint corpus).
const incoming = new Map(); // lowercase basename-without-ext -> count
const incomingByPath = new Set(); // lowercase rel paths referenced anywhere
const bump = key => incoming.set(key, (incoming.get(key) || 0) + 1);

for (const p of pages) {
  const text = stripCode(p.content);
  const checkLinks = !INFRA.has(p.base); // infra pages feed the graph, aren't link-checked

  // Wikilinks: [[target]], [[target|alias]], [[target#heading]]
  const unresolved = [];
  for (const m of text.matchAll(/\[\[([^\]|#^]+)(?:[|#^][^\]]*)?\]\]/g)) {
    const target = m[1].trim();
    if (!target) continue;
    const base = path.basename(target).replace(/\.md$/i, '').toLowerCase();
    bump(base);
    if (!basenames.has(base)) unresolved.push(target);
  }
  if (checkLinks && unresolved.length) {
    const sample = [...new Set(unresolved)].sort().slice(0, 3).map(t => `[[${t}]]`).join(' ');
    add('info', 'unresolved-wikilinks', p.rel, `${unresolved.length} body wikilink(s) with no page yet, e.g. ${sample}`);
  }

  // Frontmatter `related:` wikilinks — the documented error-severity check
  if (checkLinks && p.content.startsWith('---\n')) {
    const end = p.content.indexOf('\n---', 4);
    const fmText = end === -1 ? '' : p.content.slice(4, end);
    const relBlock = fmText.match(/^related:\s*\n((?:\s+-\s+.*\n?)*)/m);
    if (relBlock) {
      for (const m of relBlock[1].matchAll(/\[\[([^\]|#^]+)(?:[|#^][^\]]*)?\]\]/g)) {
        const base = path.basename(m[1].trim()).replace(/\.md$/i, '').toLowerCase();
        if (base && !basenames.has(base)) add('error', 'broken-related', p.rel, `related: [[${m[1].trim()}]] unresolved`);
      }
    }
  }

  // Markdown links to .md targets — checked against the real filesystem so
  // ../../raw/... targets outside the wiki/ scan root resolve correctly.
  for (const m of text.matchAll(/\]\(([^)\s]+\.md)\)/g)) {
    let target = m[1];
    if (/^[a-z]+:\/\//i.test(target)) continue; // external URL
    target = target.replace(/^<|>$/g, '');
    const abs = target.startsWith('/')
      ? path.join(VAULT, target)
      : path.resolve(path.dirname(p.file), target);
    const resolved = path.relative(VAULT, abs).replace(/\\/g, '/').toLowerCase();
    incomingByPath.add(resolved);
    bump(path.posix.basename(resolved).replace(/\.md$/, ''));
    if (checkLinks && !fs.existsSync(abs)) add('error', 'broken-mdlink', p.rel, `(${m[1]}) target missing`);
  }

  // Bare path references (index tables use `namespace/page.md` in a column).
  // Phantom check only for the catalogs — log.md rows are historical by design.
  const isCatalog = p.base === 'index.md' || p.base === '_index.md';
  for (const m of text.matchAll(/(?:^|[\s|`(])([\w][\w./-]*\.md)(?=$|[\s|`)])/gm)) {
    const resolved = path.posix.normalize(m[1]).toLowerCase();
    incomingByPath.add(resolved);
    bump(path.posix.basename(resolved).replace(/\.md$/, ''));
    if (isCatalog && !allRelPaths.has(resolved) && resolved.includes('/')) {
      add('error', 'phantom-index', p.rel, `${m[1]} listed but does not exist`);
    }
  }
}

const today = Date.now();
for (const p of pages) {
  if (INFRA.has(p.base)) continue;

  // Frontmatter
  if (!p.fm) {
    add('warning', 'no-frontmatter', p.rel, 'missing YAML frontmatter');
  } else {
    const missing = ['title', 'type', 'updated'].filter(k => !(k in p.fm));
    if (missing.length) add('info', 'frontmatter-keys', p.rel, `missing: ${missing.join(', ')}`);
  }

  // Stale
  let ts = null;
  if (p.fm && p.fm.updated) {
    const d = Date.parse(p.fm.updated);
    if (!Number.isNaN(d)) ts = d;
  }
  if (ts === null) { try { ts = fs.statSync(p.file).mtimeMs; } catch (_) { /* skip */ } }
  if (ts !== null) {
    const days = Math.floor((today - ts) / 86400000);
    if (days > STALE_DAYS) add('warning', 'stale', p.rel, `not updated in ${days} days`);
  }

  // Orphan: nothing links to it by name or path
  const base = path.basename(p.rel, '.md').toLowerCase();
  const selfRefs = new RegExp(`\\[\\[${base.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}(?:[|#^]|\\]\\])`, 'i').test(stripCode(p.content)) ? 1 : 0;
  const count = (incoming.get(base) || 0) - selfRefs;
  if (count <= 0 && !incomingByPath.has(p.rel.toLowerCase())) {
    add('info', 'orphan', p.rel, 'no incoming wikilink/md-link/index reference');
  }
}

const order = { error: 0, warning: 1, info: 2 };
findings.sort((a, b) => order[a.severity] - order[b.severity] || a.type.localeCompare(b.type) || a.page.localeCompare(b.page) || a.detail.localeCompare(b.detail));

const counts = findings.reduce((acc, f) => { acc[f.type] = (acc[f.type] || 0) + 1; return acc; }, {});
const result = {
  vault: VAULT.replace(/\\/g, '/'),
  pages_scanned: pages.length,
  pages_skipped_autogen: skippedAutogen.length,
  dirs_skipped: [...SKIP_DIRS],
  counts,
  errors: findings.filter(f => f.severity === 'error').length,
  warnings: findings.filter(f => f.severity === 'warning').length,
  info: findings.filter(f => f.severity === 'info').length,
  findings,
};

if (process.argv.includes('--json')) {
  console.log(JSON.stringify(result, null, 2));
} else {
  console.log(`wiki-lint: ${result.pages_scanned} pages scanned (${result.pages_skipped_autogen} auto-gen skipped, dirs skipped: ${result.dirs_skipped.join(', ')})`);
  console.log(`findings: ${result.errors} error / ${result.warnings} warning / ${result.info} info`);
  if (findings.length) {
    console.log('\n| Severity | Type | Page | Details |');
    console.log('|---|---|---|---|');
    for (const f of findings) console.log(`| ${f.severity} | ${f.type} | ${f.page} | ${f.detail.replace(/\|/g, '\\|')} |`);
  } else {
    console.log('Wiki health: all clear');
  }
}
